/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tsFeeDistributorV3Sol from "./TSFeeDistributor_V3.sol";
export type { tsFeeDistributorV3Sol };
import type * as tsFeeDistributorV4Sol from "./TSFeeDistributor_V4.sol";
export type { tsFeeDistributorV4Sol };
import type * as tsSushiPoolDonatorV1Sol from "./TSSushiPoolDonator_V1.sol";
export type { tsSushiPoolDonatorV1Sol };
export type { TSAggregatorTokenTransferProxy } from "./TSAggregatorTokenTransferProxy";
export type { TSFeeDistributor_V1 } from "./TSFeeDistributor_V1";
export type { TSFeeDistributor_V2 } from "./TSFeeDistributor_V2";
export type { TSOracle_V1 } from "./TSOracle_V1";
