/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRewardsReceiver } from "./IRewardsReceiver";
export type { TSFeeDistributor_V3 } from "./TSFeeDistributor_V3";
