/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IWoofi__factory } from "./IWoofi__factory";
export { TSAggregatorWoofi__factory } from "./TSAggregatorWoofi__factory";
