/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tsAggregatorWoofiSol from "./TSAggregatorWoofi.sol";
export type { tsAggregatorWoofiSol };
import type * as thorchainSimpleAggregatorV5Sol from "./ThorchainSimpleAggregatorV5.sol";
export type { thorchainSimpleAggregatorV5Sol };
import type * as chainflip from "./chainflip";
export type { chainflip };
export type { TSAggregatorGeneric_V1 } from "./TSAggregatorGeneric_V1";
export type { TSAggregatorUniswapV2_V1 } from "./TSAggregatorUniswapV2_V1";
export type { TSAggregatorUniswapV3_V1 } from "./TSAggregatorUniswapV3_V1";
export type { TSAggregatorUniswapV3_V2 } from "./TSAggregatorUniswapV3_V2";
export type { TSLendingLoop_V1 } from "./TSLendingLoop_V1";
