/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IuTHOR } from "./IuTHOR";
export type { XTHORIndividualVesting } from "./XTHORIndividualVesting";
