/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface XTHORIndividualVestingInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "beneficiary"
      | "claimRewards"
      | "claimVested"
      | "claimableAmount"
      | "claimableRewards"
      | "claimingEnabled"
      | "cliffDuration"
      | "depositUTHOR"
      | "emergencyWithdraw"
      | "emergencyWithdrawn"
      | "enableClaiming"
      | "getVestingInfo"
      | "owner"
      | "released"
      | "renounceOwnership"
      | "revokeVesting"
      | "revoked"
      | "rewardToken"
      | "startTime"
      | "totalAmount"
      | "transferOwnership"
      | "uTHOR"
      | "updateBeneficiary"
      | "vestingDuration"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BeneficiaryUpdated"
      | "ClaimingEnabled"
      | "EmergencyWithdrawUSDC"
      | "EmergencyWithdrawUTHOR"
      | "OwnershipTransferred"
      | "RewardsClaimed"
      | "TokensReleased"
      | "VestingRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "beneficiary",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimVested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimableRewards",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimingEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cliffDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "depositUTHOR",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdrawn",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "enableClaiming",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVestingInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "released", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeVesting",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "revoked", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rewardToken",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "uTHOR", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateBeneficiary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vestingDuration",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "beneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimVested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimableRewards",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimingEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cliffDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositUTHOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enableClaiming",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVestingInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "released", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeVesting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revoked", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uTHOR", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vestingDuration",
    data: BytesLike
  ): Result;
}

export namespace BeneficiaryUpdatedEvent {
  export type InputTuple = [
    oldBeneficiary: AddressLike,
    newBeneficiary: AddressLike
  ];
  export type OutputTuple = [oldBeneficiary: string, newBeneficiary: string];
  export interface OutputObject {
    oldBeneficiary: string;
    newBeneficiary: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimingEnabledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawUSDCEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EmergencyWithdrawUTHOREvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsClaimedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensReleasedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VestingRevokedEvent {
  export type InputTuple = [
    beneficiary: AddressLike,
    unvestedAmount: BigNumberish
  ];
  export type OutputTuple = [beneficiary: string, unvestedAmount: bigint];
  export interface OutputObject {
    beneficiary: string;
    unvestedAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface XTHORIndividualVesting extends BaseContract {
  connect(runner?: ContractRunner | null): XTHORIndividualVesting;
  waitForDeployment(): Promise<this>;

  interface: XTHORIndividualVestingInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  beneficiary: TypedContractMethod<[], [string], "view">;

  claimRewards: TypedContractMethod<[], [void], "nonpayable">;

  claimVested: TypedContractMethod<[], [void], "nonpayable">;

  claimableAmount: TypedContractMethod<[], [bigint], "view">;

  claimableRewards: TypedContractMethod<[], [bigint], "view">;

  claimingEnabled: TypedContractMethod<[], [boolean], "view">;

  cliffDuration: TypedContractMethod<[], [bigint], "view">;

  depositUTHOR: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<[], [void], "nonpayable">;

  emergencyWithdrawn: TypedContractMethod<[], [bigint], "view">;

  enableClaiming: TypedContractMethod<[], [void], "nonpayable">;

  getVestingInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        _totalAmount: bigint;
        _startTime: bigint;
        _cliffDuration: bigint;
        _vestingDuration: bigint;
        _released: bigint;
        _emergencyWithdrawn: bigint;
        _claimingEnabled: boolean;
        _revoked: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  released: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revokeVesting: TypedContractMethod<[], [void], "nonpayable">;

  revoked: TypedContractMethod<[], [boolean], "view">;

  rewardToken: TypedContractMethod<[], [string], "view">;

  startTime: TypedContractMethod<[], [bigint], "view">;

  totalAmount: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  uTHOR: TypedContractMethod<[], [string], "view">;

  updateBeneficiary: TypedContractMethod<
    [newBeneficiary: AddressLike],
    [void],
    "nonpayable"
  >;

  vestingDuration: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "beneficiary"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimRewards"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimVested"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimableAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimableRewards"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "claimingEnabled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "cliffDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositUTHOR"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdrawn"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "enableClaiming"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getVestingInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        _totalAmount: bigint;
        _startTime: bigint;
        _cliffDuration: bigint;
        _vestingDuration: bigint;
        _released: bigint;
        _emergencyWithdrawn: bigint;
        _claimingEnabled: boolean;
        _revoked: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "released"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeVesting"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revoked"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rewardToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uTHOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateBeneficiary"
  ): TypedContractMethod<[newBeneficiary: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vestingDuration"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "BeneficiaryUpdated"
  ): TypedContractEvent<
    BeneficiaryUpdatedEvent.InputTuple,
    BeneficiaryUpdatedEvent.OutputTuple,
    BeneficiaryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimingEnabled"
  ): TypedContractEvent<
    ClaimingEnabledEvent.InputTuple,
    ClaimingEnabledEvent.OutputTuple,
    ClaimingEnabledEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawUSDC"
  ): TypedContractEvent<
    EmergencyWithdrawUSDCEvent.InputTuple,
    EmergencyWithdrawUSDCEvent.OutputTuple,
    EmergencyWithdrawUSDCEvent.OutputObject
  >;
  getEvent(
    key: "EmergencyWithdrawUTHOR"
  ): TypedContractEvent<
    EmergencyWithdrawUTHOREvent.InputTuple,
    EmergencyWithdrawUTHOREvent.OutputTuple,
    EmergencyWithdrawUTHOREvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RewardsClaimed"
  ): TypedContractEvent<
    RewardsClaimedEvent.InputTuple,
    RewardsClaimedEvent.OutputTuple,
    RewardsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TokensReleased"
  ): TypedContractEvent<
    TokensReleasedEvent.InputTuple,
    TokensReleasedEvent.OutputTuple,
    TokensReleasedEvent.OutputObject
  >;
  getEvent(
    key: "VestingRevoked"
  ): TypedContractEvent<
    VestingRevokedEvent.InputTuple,
    VestingRevokedEvent.OutputTuple,
    VestingRevokedEvent.OutputObject
  >;

  filters: {
    "BeneficiaryUpdated(address,address)": TypedContractEvent<
      BeneficiaryUpdatedEvent.InputTuple,
      BeneficiaryUpdatedEvent.OutputTuple,
      BeneficiaryUpdatedEvent.OutputObject
    >;
    BeneficiaryUpdated: TypedContractEvent<
      BeneficiaryUpdatedEvent.InputTuple,
      BeneficiaryUpdatedEvent.OutputTuple,
      BeneficiaryUpdatedEvent.OutputObject
    >;

    "ClaimingEnabled()": TypedContractEvent<
      ClaimingEnabledEvent.InputTuple,
      ClaimingEnabledEvent.OutputTuple,
      ClaimingEnabledEvent.OutputObject
    >;
    ClaimingEnabled: TypedContractEvent<
      ClaimingEnabledEvent.InputTuple,
      ClaimingEnabledEvent.OutputTuple,
      ClaimingEnabledEvent.OutputObject
    >;

    "EmergencyWithdrawUSDC(uint256)": TypedContractEvent<
      EmergencyWithdrawUSDCEvent.InputTuple,
      EmergencyWithdrawUSDCEvent.OutputTuple,
      EmergencyWithdrawUSDCEvent.OutputObject
    >;
    EmergencyWithdrawUSDC: TypedContractEvent<
      EmergencyWithdrawUSDCEvent.InputTuple,
      EmergencyWithdrawUSDCEvent.OutputTuple,
      EmergencyWithdrawUSDCEvent.OutputObject
    >;

    "EmergencyWithdrawUTHOR(uint256)": TypedContractEvent<
      EmergencyWithdrawUTHOREvent.InputTuple,
      EmergencyWithdrawUTHOREvent.OutputTuple,
      EmergencyWithdrawUTHOREvent.OutputObject
    >;
    EmergencyWithdrawUTHOR: TypedContractEvent<
      EmergencyWithdrawUTHOREvent.InputTuple,
      EmergencyWithdrawUTHOREvent.OutputTuple,
      EmergencyWithdrawUTHOREvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RewardsClaimed(uint256)": TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;
    RewardsClaimed: TypedContractEvent<
      RewardsClaimedEvent.InputTuple,
      RewardsClaimedEvent.OutputTuple,
      RewardsClaimedEvent.OutputObject
    >;

    "TokensReleased(uint256)": TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;
    TokensReleased: TypedContractEvent<
      TokensReleasedEvent.InputTuple,
      TokensReleasedEvent.OutputTuple,
      TokensReleasedEvent.OutputObject
    >;

    "VestingRevoked(address,uint256)": TypedContractEvent<
      VestingRevokedEvent.InputTuple,
      VestingRevokedEvent.OutputTuple,
      VestingRevokedEvent.OutputObject
    >;
    VestingRevoked: TypedContractEvent<
      VestingRevokedEvent.InputTuple,
      VestingRevokedEvent.OutputTuple,
      VestingRevokedEvent.OutputObject
    >;
  };
}
