/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as skChainflipHyperliquidV1Sol from "./SKChainflipHyperliquid_V1.sol";
export type { skChainflipHyperliquidV1Sol };
export type { TSAggregatorChainflip_V1 } from "./TSAggregatorChainflip_V1";
