/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'TSAggregatorTokenTransferProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSAggregatorTokenTransferProxy__factory>
getContractFactory(name: 'TSFeeDistributor_V1', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSFeeDistributor_V1__factory>
getContractFactory(name: 'TSFeeDistributor_V2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSFeeDistributor_V2__factory>
getContractFactory(name: 'IRewardsReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRewardsReceiver__factory>
getContractFactory(name: 'TSFeeDistributor_V3', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSFeeDistributor_V3__factory>
getContractFactory(name: 'IRewardsReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRewardsReceiver__factory>
getContractFactory(name: 'TSFeeDistributor_V4', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSFeeDistributor_V4__factory>
getContractFactory(name: 'IRewardsReceiver', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRewardsReceiver__factory>
getContractFactory(name: 'TSFeeDistributor_V5', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSFeeDistributor_V5__factory>
getContractFactory(name: 'TSOracle_V1', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSOracle_V1__factory>
getContractFactory(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IUniswapV2Pair__factory>
getContractFactory(name: 'TSSushiPoolDonator_V1', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TSSushiPoolDonator_V1__factory>

  getContractAt(name: 'TSAggregatorTokenTransferProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSAggregatorTokenTransferProxy>
getContractAt(name: 'TSFeeDistributor_V1', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSFeeDistributor_V1>
getContractAt(name: 'TSFeeDistributor_V2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSFeeDistributor_V2>
getContractAt(name: 'IRewardsReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRewardsReceiver>
getContractAt(name: 'TSFeeDistributor_V3', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSFeeDistributor_V3>
getContractAt(name: 'IRewardsReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRewardsReceiver>
getContractAt(name: 'TSFeeDistributor_V4', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSFeeDistributor_V4>
getContractAt(name: 'IRewardsReceiver', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRewardsReceiver>
getContractAt(name: 'TSFeeDistributor_V5', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSFeeDistributor_V5>
getContractAt(name: 'TSOracle_V1', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSOracle_V1>
getContractAt(name: 'IUniswapV2Pair', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IUniswapV2Pair>
getContractAt(name: 'TSSushiPoolDonator_V1', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TSSushiPoolDonator_V1>

  deployContract(name: 'TSAggregatorTokenTransferProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSAggregatorTokenTransferProxy>
deployContract(name: 'TSFeeDistributor_V1', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V1>
deployContract(name: 'TSFeeDistributor_V2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V2>
deployContract(name: 'IRewardsReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardsReceiver>
deployContract(name: 'TSFeeDistributor_V3', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V3>
deployContract(name: 'IRewardsReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardsReceiver>
deployContract(name: 'TSFeeDistributor_V4', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V4>
deployContract(name: 'IRewardsReceiver', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardsReceiver>
deployContract(name: 'TSFeeDistributor_V5', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V5>
deployContract(name: 'TSOracle_V1', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSOracle_V1>
deployContract(name: 'IUniswapV2Pair', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'TSSushiPoolDonator_V1', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSSushiPoolDonator_V1>

  deployContract(name: 'TSAggregatorTokenTransferProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSAggregatorTokenTransferProxy>
deployContract(name: 'TSFeeDistributor_V1', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V1>
deployContract(name: 'TSFeeDistributor_V2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V2>
deployContract(name: 'IRewardsReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardsReceiver>
deployContract(name: 'TSFeeDistributor_V3', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V3>
deployContract(name: 'IRewardsReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardsReceiver>
deployContract(name: 'TSFeeDistributor_V4', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V4>
deployContract(name: 'IRewardsReceiver', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRewardsReceiver>
deployContract(name: 'TSFeeDistributor_V5', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSFeeDistributor_V5>
deployContract(name: 'TSOracle_V1', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSOracle_V1>
deployContract(name: 'IUniswapV2Pair', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IUniswapV2Pair>
deployContract(name: 'TSSushiPoolDonator_V1', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TSSushiPoolDonator_V1>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  