/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TSAggregatorTokenTransferProxyInterface extends Interface {
    getFunction(nameOrSignature: "owners" | "setOwner" | "transferTokens"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnerSet"): EventFragment;

    encodeFunctionData(functionFragment: 'owners', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferTokens', values: [AddressLike, AddressLike, AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferTokens', data: BytesLike): Result;
  }

  
    export namespace OwnerSetEvent {
      export type InputTuple = [owner: AddressLike, active: boolean];
      export type OutputTuple = [owner: string, active: boolean];
      export interface OutputObject {owner: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TSAggregatorTokenTransferProxy extends BaseContract {
    
    connect(runner?: ContractRunner | null): TSAggregatorTokenTransferProxy;
    waitForDeployment(): Promise<this>;

    interface: TSAggregatorTokenTransferProxyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    owners: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    setOwner: TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    transferTokens: TypedContractMethod<
      [token: AddressLike, from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferTokens'): TypedContractMethod<
      [token: AddressLike, from: AddressLike, to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnerSet'): TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;

    filters: {
      
      'OwnerSet(address,bool)': TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
      OwnerSet: TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
    
    };
  }