/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TSFeeDistributor_V1Interface extends Interface {
    getFunction(nameOrSignature: "communityBps" | "communityIndex" | "distributeCommunity" | "distributeCommunityExecutor" | "distributeTreasury" | "distributeTreasuryExecutor" | "executors" | "feeAsset" | "getMemoCommunity" | "getMemoTreasury" | "memoCommunity" | "memoTreasury" | "minFeeAmount" | "oracle" | "owners" | "publicMode" | "setCommunityIndex" | "setExecutor" | "setMemoCommunity" | "setMemoTreasury" | "setMinFeeAmount" | "setOwner" | "setShares" | "setTCRouter" | "setTreasuryIndex" | "setTreasuryWallet" | "tcRouter" | "transferTreasury" | "treasuryBps" | "treasuryIndex" | "treasuryWallet"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CommunityDistribution" | "ExecutorSet" | "OwnerSet" | "TreasuryDistribution"): EventFragment;

    encodeFunctionData(functionFragment: 'communityBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'communityIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'distributeCommunity', values?: undefined): string;
encodeFunctionData(functionFragment: 'distributeCommunityExecutor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'distributeTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'distributeTreasuryExecutor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'executors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'feeAsset', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMemoCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMemoTreasury', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'memoCommunity', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'memoTreasury', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'minFeeAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'oracle', values?: undefined): string;
encodeFunctionData(functionFragment: 'owners', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'publicMode', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCommunityIndex', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setExecutor', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setMemoCommunity', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'setMemoTreasury', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'setMinFeeAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setShares', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTCRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setTreasuryIndex', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasuryWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tcRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryIndex', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryWallet', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'communityBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'communityIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeCommunityExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distributeTreasuryExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMemoCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMemoTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'memoCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'memoTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'minFeeAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'oracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publicMode', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCommunityIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMemoCommunity', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMemoTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMinFeeAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTCRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasuryIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasuryWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryIndex', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryWallet', data: BytesLike): Result;
  }

  
    export namespace CommunityDistributionEvent {
      export type InputTuple = [amount: BigNumberish, memo: string];
      export type OutputTuple = [amount: bigint, memo: string];
      export interface OutputObject {amount: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutorSetEvent {
      export type InputTuple = [executor: AddressLike, active: boolean];
      export type OutputTuple = [executor: string, active: boolean];
      export interface OutputObject {executor: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerSetEvent {
      export type InputTuple = [owner: AddressLike, active: boolean];
      export type OutputTuple = [owner: string, active: boolean];
      export interface OutputObject {owner: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryDistributionEvent {
      export type InputTuple = [amount: BigNumberish, memo: string];
      export type OutputTuple = [amount: bigint, memo: string];
      export interface OutputObject {amount: bigint, memo: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TSFeeDistributor_V1 extends BaseContract {
    
    connect(runner?: ContractRunner | null): TSFeeDistributor_V1;
    waitForDeployment(): Promise<this>;

    interface: TSFeeDistributor_V1Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    communityBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    communityIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    distributeCommunity: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    distributeCommunityExecutor: TypedContractMethod<
      [inboundAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    distributeTreasury: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    distributeTreasuryExecutor: TypedContractMethod<
      [inboundAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    executors: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    feeAsset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getMemoCommunity: TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getMemoTreasury: TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >
    

    
    memoCommunity: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    memoTreasury: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    minFeeAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    oracle: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owners: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    publicMode: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setCommunityIndex: TypedContractMethod<
      [index: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setExecutor: TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setMemoCommunity: TypedContractMethod<
      [id: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    setMemoTreasury: TypedContractMethod<
      [id: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >
    

    
    setMinFeeAmount: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setOwner: TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setShares: TypedContractMethod<
      [treasury: BigNumberish, community: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTCRouter: TypedContractMethod<
      [_tcRouterAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasuryIndex: TypedContractMethod<
      [index: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasuryWallet: TypedContractMethod<
      [_treasuryWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tcRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferTreasury: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    treasuryBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    treasuryIndex: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    treasuryWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'communityBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'communityIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'distributeCommunity'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeCommunityExecutor'): TypedContractMethod<
      [inboundAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeTreasury'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'distributeTreasuryExecutor'): TypedContractMethod<
      [inboundAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'feeAsset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMemoCommunity'): TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getMemoTreasury'): TypedContractMethod<
      [id: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'memoCommunity'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'memoTreasury'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'minFeeAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'oracle'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'publicMode'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setCommunityIndex'): TypedContractMethod<
      [index: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setExecutor'): TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMemoCommunity'): TypedContractMethod<
      [id: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMemoTreasury'): TypedContractMethod<
      [id: BigNumberish, memo: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setMinFeeAmount'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setShares'): TypedContractMethod<
      [treasury: BigNumberish, community: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTCRouter'): TypedContractMethod<
      [_tcRouterAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasuryIndex'): TypedContractMethod<
      [index: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasuryWallet'): TypedContractMethod<
      [_treasuryWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tcRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferTreasury'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryIndex'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'CommunityDistribution'): TypedContractEvent<CommunityDistributionEvent.InputTuple, CommunityDistributionEvent.OutputTuple, CommunityDistributionEvent.OutputObject>;
getEvent(key: 'ExecutorSet'): TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
getEvent(key: 'OwnerSet'): TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
getEvent(key: 'TreasuryDistribution'): TypedContractEvent<TreasuryDistributionEvent.InputTuple, TreasuryDistributionEvent.OutputTuple, TreasuryDistributionEvent.OutputObject>;

    filters: {
      
      'CommunityDistribution(uint256,string)': TypedContractEvent<CommunityDistributionEvent.InputTuple, CommunityDistributionEvent.OutputTuple, CommunityDistributionEvent.OutputObject>;
      CommunityDistribution: TypedContractEvent<CommunityDistributionEvent.InputTuple, CommunityDistributionEvent.OutputTuple, CommunityDistributionEvent.OutputObject>;
    

      'ExecutorSet(address,bool)': TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
      ExecutorSet: TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
    

      'OwnerSet(address,bool)': TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
      OwnerSet: TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
    

      'TreasuryDistribution(uint256,string)': TypedContractEvent<TreasuryDistributionEvent.InputTuple, TreasuryDistributionEvent.OutputTuple, TreasuryDistributionEvent.OutputObject>;
      TreasuryDistribution: TypedContractEvent<TreasuryDistributionEvent.InputTuple, TreasuryDistributionEvent.OutputTuple, TreasuryDistributionEvent.OutputObject>;
    
    };
  }