/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TSOracle_V1Interface extends Interface {
    getFunction(nameOrSignature: "changeExpiration" | "executors" | "expiration" | "feeAmount" | "feeToken" | "getAccessExpiry" | "getInboundAddress" | "getPoolsAPY" | "getRouterAddress" | "getSaversAPY" | "grantAccess" | "owners" | "pay" | "poolsAPYUpdatedAt" | "routerAddressUpdatedAt" | "saversAPYUpdatedAt" | "setExecutor" | "setOwner" | "updateFeeAmount" | "updatePoolsAPY" | "updateRouterAddress" | "updateSaversAPY" | "updateVaults" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AccessGranted" | "ExecutorSet" | "ExpirationChanged" | "OwnerSet" | "PaymentReceived" | "VaultsUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'changeExpiration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'executors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'expiration', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeAmount', values?: undefined): string;
encodeFunctionData(functionFragment: 'feeToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAccessExpiry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getInboundAddress', values: [string]): string;
encodeFunctionData(functionFragment: 'getPoolsAPY', values: [string]): string;
encodeFunctionData(functionFragment: 'getRouterAddress', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSaversAPY', values: [string]): string;
encodeFunctionData(functionFragment: 'grantAccess', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owners', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'pay', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'poolsAPYUpdatedAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'routerAddressUpdatedAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'saversAPYUpdatedAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'setExecutor', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'updateFeeAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updatePoolsAPY', values: [string[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'updateRouterAddress', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateSaversAPY', values: [string[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'updateVaults', values: [string[], BytesLike[], boolean[], boolean[]]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'changeExpiration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'expiration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccessExpiry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInboundAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoolsAPY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRouterAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSaversAPY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantAccess', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pay', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'poolsAPYUpdatedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'routerAddressUpdatedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'saversAPYUpdatedAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateFeeAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePoolsAPY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateRouterAddress', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSaversAPY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateVaults', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AccessGrantedEvent {
      export type InputTuple = [user: AddressLike, expiry: BigNumberish];
      export type OutputTuple = [user: string, expiry: bigint];
      export interface OutputObject {user: string, expiry: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutorSetEvent {
      export type InputTuple = [executor: AddressLike, active: boolean];
      export type OutputTuple = [executor: string, active: boolean];
      export interface OutputObject {executor: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExpirationChangedEvent {
      export type InputTuple = [newExpiration: BigNumberish];
      export type OutputTuple = [newExpiration: bigint];
      export interface OutputObject {newExpiration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerSetEvent {
      export type InputTuple = [owner: AddressLike, active: boolean];
      export type OutputTuple = [owner: string, active: boolean];
      export interface OutputObject {owner: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PaymentReceivedEvent {
      export type InputTuple = [user: AddressLike, amount: BigNumberish, expiry: BigNumberish];
      export type OutputTuple = [user: string, amount: bigint, expiry: bigint];
      export interface OutputObject {user: string, amount: bigint, expiry: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VaultsUpdatedEvent {
      export type InputTuple = [chains: string[], timestamp: BigNumberish];
      export type OutputTuple = [chains: string[], timestamp: bigint];
      export interface OutputObject {chains: string[], timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TSOracle_V1 extends BaseContract {
    
    connect(runner?: ContractRunner | null): TSOracle_V1;
    waitForDeployment(): Promise<this>;

    interface: TSOracle_V1Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    changeExpiration: TypedContractMethod<
      [newExpiration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    executors: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    expiration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeAmount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    feeToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getAccessExpiry: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getInboundAddress: TypedContractMethod<
      [chain: string, ],
      [[string, string]],
      'view'
    >
    

    
    getPoolsAPY: TypedContractMethod<
      [chain: string, ],
      [bigint],
      'view'
    >
    

    
    getRouterAddress: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getSaversAPY: TypedContractMethod<
      [chain: string, ],
      [bigint],
      'view'
    >
    

    
    grantAccess: TypedContractMethod<
      [user: AddressLike, accessExpiry: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owners: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    pay: TypedContractMethod<
      [clientAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    poolsAPYUpdatedAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    routerAddressUpdatedAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    saversAPYUpdatedAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setExecutor: TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setOwner: TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    updateFeeAmount: TypedContractMethod<
      [newFeeAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updatePoolsAPY: TypedContractMethod<
      [chains: string[], apys: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    updateRouterAddress: TypedContractMethod<
      [_tcRouterAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateSaversAPY: TypedContractMethod<
      [chains: string[], apys: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    updateVaults: TypedContractMethod<
      [chains: string[], newAddresses: BytesLike[], tradingStatuses: boolean[], isEvm: boolean[], ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [recipient: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'changeExpiration'): TypedContractMethod<
      [newExpiration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'expiration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeAmount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'feeToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getAccessExpiry'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getInboundAddress'): TypedContractMethod<
      [chain: string, ],
      [[string, string]],
      'view'
    >;
getFunction(nameOrSignature: 'getPoolsAPY'): TypedContractMethod<
      [chain: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getRouterAddress'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getSaversAPY'): TypedContractMethod<
      [chain: string, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'grantAccess'): TypedContractMethod<
      [user: AddressLike, accessExpiry: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pay'): TypedContractMethod<
      [clientAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'poolsAPYUpdatedAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'routerAddressUpdatedAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'saversAPYUpdatedAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setExecutor'): TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateFeeAmount'): TypedContractMethod<
      [newFeeAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePoolsAPY'): TypedContractMethod<
      [chains: string[], apys: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateRouterAddress'): TypedContractMethod<
      [_tcRouterAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSaversAPY'): TypedContractMethod<
      [chains: string[], apys: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateVaults'): TypedContractMethod<
      [chains: string[], newAddresses: BytesLike[], tradingStatuses: boolean[], isEvm: boolean[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [recipient: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AccessGranted'): TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
getEvent(key: 'ExecutorSet'): TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
getEvent(key: 'ExpirationChanged'): TypedContractEvent<ExpirationChangedEvent.InputTuple, ExpirationChangedEvent.OutputTuple, ExpirationChangedEvent.OutputObject>;
getEvent(key: 'OwnerSet'): TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
getEvent(key: 'PaymentReceived'): TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;
getEvent(key: 'VaultsUpdated'): TypedContractEvent<VaultsUpdatedEvent.InputTuple, VaultsUpdatedEvent.OutputTuple, VaultsUpdatedEvent.OutputObject>;

    filters: {
      
      'AccessGranted(address,uint256)': TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
      AccessGranted: TypedContractEvent<AccessGrantedEvent.InputTuple, AccessGrantedEvent.OutputTuple, AccessGrantedEvent.OutputObject>;
    

      'ExecutorSet(address,bool)': TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
      ExecutorSet: TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
    

      'ExpirationChanged(uint32)': TypedContractEvent<ExpirationChangedEvent.InputTuple, ExpirationChangedEvent.OutputTuple, ExpirationChangedEvent.OutputObject>;
      ExpirationChanged: TypedContractEvent<ExpirationChangedEvent.InputTuple, ExpirationChangedEvent.OutputTuple, ExpirationChangedEvent.OutputObject>;
    

      'OwnerSet(address,bool)': TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
      OwnerSet: TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
    

      'PaymentReceived(address,uint256,uint256)': TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;
      PaymentReceived: TypedContractEvent<PaymentReceivedEvent.InputTuple, PaymentReceivedEvent.OutputTuple, PaymentReceivedEvent.OutputObject>;
    

      'VaultsUpdated(string[],uint256)': TypedContractEvent<VaultsUpdatedEvent.InputTuple, VaultsUpdatedEvent.OutputTuple, VaultsUpdatedEvent.OutputObject>;
      VaultsUpdated: TypedContractEvent<VaultsUpdatedEvent.InputTuple, VaultsUpdatedEvent.OutputTuple, VaultsUpdatedEvent.OutputObject>;
    
    };
  }