/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IRewardsReceiver, IRewardsReceiverInterface } from "../../TSFeeDistributor_V3.sol/IRewardsReceiver.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "depositRewards",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IRewardsReceiver__factory {
    static readonly abi = _abi;
    static createInterface(): IRewardsReceiverInterface {
      return new Interface(_abi) as IRewardsReceiverInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IRewardsReceiver {
      return new Contract(address, _abi, runner) as unknown as IRewardsReceiver;
    }
  }
  