/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TSFeeDistributor_V3Interface extends Interface {
    getFunction(nameOrSignature: "communityPreciseBps" | "distribute" | "executors" | "feeAsset" | "owners" | "rewardAmountThreshold" | "setExecutor" | "setOwner" | "setShares" | "setTCRouter" | "setThreshold" | "setTreasuryWallet" | "tcRouter" | "thorPoolPreciseBps" | "thorToken" | "treasuryPreciseBps" | "treasuryWallet" | "uThorPreciseBps" | "uThorToken" | "vThorPreciseBps" | "vThorToken" | "yThorPreciseBps" | "yThorToken"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Distribution" | "ExecutorSet" | "OwnerSet"): EventFragment;

    encodeFunctionData(functionFragment: 'communityPreciseBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'distribute', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'executors', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'feeAsset', values?: undefined): string;
encodeFunctionData(functionFragment: 'owners', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rewardAmountThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'setExecutor', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setOwner', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setShares', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTCRouter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setThreshold', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasuryWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'tcRouter', values?: undefined): string;
encodeFunctionData(functionFragment: 'thorPoolPreciseBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'thorToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryPreciseBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasuryWallet', values?: undefined): string;
encodeFunctionData(functionFragment: 'uThorPreciseBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'uThorToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'vThorPreciseBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'vThorToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'yThorPreciseBps', values?: undefined): string;
encodeFunctionData(functionFragment: 'yThorToken', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'communityPreciseBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'distribute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'executors', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'feeAsset', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owners', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardAmountThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setExecutor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setShares', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTCRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasuryWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tcRouter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'thorPoolPreciseBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'thorToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryPreciseBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasuryWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uThorPreciseBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uThorToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vThorPreciseBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vThorToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yThorPreciseBps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'yThorToken', data: BytesLike): Result;
  }

  
    export namespace DistributionEvent {
      export type InputTuple = [amount: BigNumberish, poolBps: BigNumberish, uThorBps: BigNumberish, vThorBps: BigNumberish, yThorBps: BigNumberish];
      export type OutputTuple = [amount: bigint, poolBps: bigint, uThorBps: bigint, vThorBps: bigint, yThorBps: bigint];
      export interface OutputObject {amount: bigint, poolBps: bigint, uThorBps: bigint, vThorBps: bigint, yThorBps: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ExecutorSetEvent {
      export type InputTuple = [executor: AddressLike, active: boolean];
      export type OutputTuple = [executor: string, active: boolean];
      export interface OutputObject {executor: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnerSetEvent {
      export type InputTuple = [owner: AddressLike, active: boolean];
      export type OutputTuple = [owner: string, active: boolean];
      export interface OutputObject {owner: string, active: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TSFeeDistributor_V3 extends BaseContract {
    
    connect(runner?: ContractRunner | null): TSFeeDistributor_V3;
    waitForDeployment(): Promise<this>;

    interface: TSFeeDistributor_V3Interface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    communityPreciseBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    distribute: TypedContractMethod<
      [inboundAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    executors: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    feeAsset: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owners: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    rewardAmountThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setExecutor: TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setOwner: TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setShares: TypedContractMethod<
      [_treasuryPreciseBps: BigNumberish, _communityPreciseBps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTCRouter: TypedContractMethod<
      [_tcRouterAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setThreshold: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasuryWallet: TypedContractMethod<
      [_treasuryWallet: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tcRouter: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    thorPoolPreciseBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    thorToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    treasuryPreciseBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    treasuryWallet: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    uThorPreciseBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    uThorToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    vThorPreciseBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    vThorToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    yThorPreciseBps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    yThorToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'communityPreciseBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'distribute'): TypedContractMethod<
      [inboundAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'executors'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'feeAsset'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owners'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'rewardAmountThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setExecutor'): TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setOwner'): TypedContractMethod<
      [owner: AddressLike, active: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setShares'): TypedContractMethod<
      [_treasuryPreciseBps: BigNumberish, _communityPreciseBps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTCRouter'): TypedContractMethod<
      [_tcRouterAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setThreshold'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasuryWallet'): TypedContractMethod<
      [_treasuryWallet: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tcRouter'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'thorPoolPreciseBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'thorToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryPreciseBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'treasuryWallet'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'uThorPreciseBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'uThorToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'vThorPreciseBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'vThorToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'yThorPreciseBps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'yThorToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'Distribution'): TypedContractEvent<DistributionEvent.InputTuple, DistributionEvent.OutputTuple, DistributionEvent.OutputObject>;
getEvent(key: 'ExecutorSet'): TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
getEvent(key: 'OwnerSet'): TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;

    filters: {
      
      'Distribution(uint256,uint32,uint32,uint32,uint32)': TypedContractEvent<DistributionEvent.InputTuple, DistributionEvent.OutputTuple, DistributionEvent.OutputObject>;
      Distribution: TypedContractEvent<DistributionEvent.InputTuple, DistributionEvent.OutputTuple, DistributionEvent.OutputObject>;
    

      'ExecutorSet(address,bool)': TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
      ExecutorSet: TypedContractEvent<ExecutorSetEvent.InputTuple, ExecutorSetEvent.OutputTuple, ExecutorSetEvent.OutputObject>;
    

      'OwnerSet(address,bool)': TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
      OwnerSet: TypedContractEvent<OwnerSetEvent.InputTuple, OwnerSetEvent.OutputTuple, OwnerSetEvent.OutputObject>;
    
    };
  }