/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IUniswapV2Pair, IUniswapV2PairInterface } from "../../TSSushiPoolDonator_V1.sol/IUniswapV2Pair.js";

  const _abi = [
  {
    "inputs": [],
    "name": "sync",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IUniswapV2Pair__factory {
    static readonly abi = _abi;
    static createInterface(): IUniswapV2PairInterface {
      return new Interface(_abi) as IUniswapV2PairInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IUniswapV2Pair {
      return new Contract(address, _abi, runner) as unknown as IUniswapV2Pair;
    }
  }
  