/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, AddressLike, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { TSSushiPoolDonator_V1, TSSushiPoolDonator_V1Interface } from "../../TSSushiPoolDonator_V1.sol/TSSushiPoolDonator_V1.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_wethAddress",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "_pairAddress",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "pairAddress",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "wethAddress",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "stateMutability": "payable",
    "type": "receive"
  }
] as const;

  const _bytecode = "0x608060405234801561000f575f80fd5b5060405161031e38038061031e83398101604081905261002e91610079565b5f80546001600160a01b039384166001600160a01b031991821617909155600180549290931691161790556100aa565b80516001600160a01b0381168114610074575f80fd5b919050565b5f806040838503121561008a575f80fd5b6100938361005e565b91506100a16020840161005e565b90509250929050565b610267806100b75f395ff3fe60806040526004361061002b575f3560e01c80634f0e0ef3146101b2578063a8b08982146101ec575f80fd5b366101ae575f8054906101000a90046001600160a01b03166001600160a01b031663d0e30db0346040518263ffffffff1660e01b81526004015f604051808303818588803b15801561007b575f80fd5b505af115801561008d573d5f803e3d5ffd5b50505f5460015460405163a9059cbb60e01b81526001600160a01b0391821660048201523460248201529116935063a9059cbb925060440190506020604051808303815f875af11580156100e3573d5f803e3d5ffd5b505050506040513d601f19601f82011682018060405250810190610107919061020b565b61014e5760405162461bcd60e51b815260206004820152601460248201527315d15512081d1c985b9cd9995c8819985a5b195960621b604482015260640160405180910390fd5b60015f9054906101000a90046001600160a01b03166001600160a01b031663fff6cae96040518163ffffffff1660e01b81526004015f604051808303815f87803b15801561019a575f80fd5b505af11580156101ac573d5f803e3d5ffd5b005b5f80fd5b3480156101bd575f80fd5b505f546101d0906001600160a01b031681565b6040516001600160a01b03909116815260200160405180910390f35b3480156101f7575f80fd5b506001546101d0906001600160a01b031681565b5f6020828403121561021b575f80fd5b8151801515811461022a575f80fd5b939250505056fea2646970667358221220d7b5e18c1f71519b5b5b3b146b31266866a6e4d102951b1d63d973d9fca2ed0464736f6c63430008160033";

  
      type TSSushiPoolDonator_V1ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: TSSushiPoolDonator_V1ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class TSSushiPoolDonator_V1__factory extends ContractFactory {
    
      constructor(...args: TSSushiPoolDonator_V1ConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(_wethAddress: AddressLike, _pairAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(_wethAddress, _pairAddress, overrides || {});
    };
    override deploy(_wethAddress: AddressLike, _pairAddress: AddressLike, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(_wethAddress, _pairAddress, overrides || {}) as Promise<TSSushiPoolDonator_V1 & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): TSSushiPoolDonator_V1__factory {
      return super.connect(runner) as TSSushiPoolDonator_V1__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): TSSushiPoolDonator_V1Interface {
      return new Interface(_abi) as TSSushiPoolDonator_V1Interface;
    }
    
    override attach(address: string | Addressable): TSSushiPoolDonator_V1 {
      return super.attach(address) as TSSushiPoolDonator_V1;
    }
  static connect(address: string, runner?: ContractRunner | null): TSSushiPoolDonator_V1 {
      return new Contract(address, _abi, runner) as unknown as TSSushiPoolDonator_V1;
    }
  }

  
  