/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20Permit } from "./ERC20Permit";
export type { ERC20Vote } from "./ERC20Vote";
export type { Executors } from "./Executors";
export type { Owners } from "./Owners";
