/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as tsSwapGenericV2Sol from "./TSSwapGeneric_V2.sol";
export type { tsSwapGenericV2Sol };
export type { TSWrapperLedger_V1 } from "./TSWrapperLedger_V1";
export type { TSWrapperTCRouterV4_V1 } from "./TSWrapperTCRouterV4_V1";
