/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IRewardsReceiver } from './IRewardsReceiver.js';
export type { TSFeeDistributor_V5 } from './TSFeeDistributor_V5.js';